//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinema.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int IdTicket { get; set; }
        public bool Status { get; set; }
        public string Row { get; set; }
        public string Col { get; set; }
        public bool IsBuy { get; set; }
    
        public virtual Sessions Sessions { get; set; }
        public virtual Order Order { get; set; }
    }
}
